Add a public method to focus the component
Blazored/Typeahead pull request #166
Opened 2020-09-16 02:49 UTC by kiasyn

Addresses issue #150

2020-09-18 06:30 UTC, chrissainty requested changes
This looks great @kiasyn. Just need a couple of things before I can merge it though:

1. Could you update the Blazor Server sample with the example as well
2. Could you add a some details to the readme so people know this feature exists and how to use it

Once these bit are done, this can be merged straight away

2020-11-16 07:49 UTC, zippo-lighter commented
@chrissainty what is blocking the merge into the main repository?

2020-11-16 20:23 UTC, chrissainty commented
@zippo-lighter As per the comment directly above yours states, there is no documentation or samples for this work.

2020-12-11 19:44 UTC, chrissainty approved these changes

2020-12-11 19:44 UTC, merged