Added possibility to add an item when no item is found
Blazored/Typeahead pull request #215
Opened 2021-03-17 16:53 UTC by matijs-toonen

## Situation
I would like to have the possibility to add an item using the typeahead component without the need to submit a form with all its data. This would be useful in cases like a label which is nothing more than plain text.

## Description
This PR will add a new parameter to the typeahead component called `AddItemOnEmptyResultMethod`,
the parameter will change the `NotFoundTemplate` to be a selectable item just like the search results, this item will however use the `NotFoundTemplate` as the Template instead of the `ResultTemplate`.

2021-03-20 15:21 UTC, chrissainty requested changes
This is some great work @matijs-toonen! I've just got one change request but then it's ready to merge. This will make a lot of people very happy!

2021-03-20 15:21 UTC, chrissainty commented on samples/BlazorServer/BlazorServer.csproj
> +    <TargetFramework>net5.0</TargetFramework>
Could you undo this change. We're keeping the library compatible with 3.x for now.

2021-03-22 18:21 UTC, kinetiq commented
@chrissainty Cindy found this PR, and wondered if this might indirectly address the need we were talking about on Twitter. To recap, we want users to be able to type text into the TypeAhead that does not exist in the list, and potentially use use that. Currently we do have a way to get at that text, but if the TypeAhead loses focus, the text is cleared. 

Any thoughts?

2021-03-22 18:50 UTC, chrissainty commented
Hey @kinetiq. Yes Cindy messaged me earlier and I pointed her at this PR. It was a very odd, but great, coincidence this popped up when it did. It seems to me like it would solve your issue. @matijs-toonen did some great work here.

2021-03-22 18:52 UTC, chrissainty approved these changes

2021-03-22 18:52 UTC, merged

2021-03-22 18:53 UTC, chrissainty commented
Thanks for this great feature @matijs-toonen! :shipit:

2021-03-22 20:10 UTC, kinetiq commented
Well that case - thanks @matijs-toonen, what a wonderful coincidence. :) I really appreciate your contribution. Turns out it will solve a headache for my team.

Chris, any idea when this will be available in nuget?

2021-03-27 08:24 UTC, chrissainty commented
@kinetiq I plan on getting this released today.